package abcrun

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/harneet2512/gtm-work/core-go/internal/orchestrator"
	"github.com/harneet2512/gtm-work/core-go/internal/workerclient"
	"slices"
)

// setStore makes the table hold exactly these items (no work if it already does) and runs the hard block on it.
func (r *Runner) setStore(ctx context.Context, items []LearnedItem) error {
	want := ids(items)
	if !slices.Equal(want, r.installd) {
		if err := ReplaceStore(ctx, r.o.DB, r.o.Rules, items); err != nil {
			return err
		}
		r.installd = want
	}
	if r.o.Guard != nil {
		stored, err := ExportStore(ctx, r.o.DB)
		if err != nil {
			return err
		}
		return r.o.Guard(ctx, stored, true)
	}
	return nil
}

// armWithA runs one run with the counterfactual on: the arm named label reads items, and arm A is the same state with
// the guidance withheld (E7), generated by the same run.
func (r *Runner) armWithA(ctx context.Context, s Situation, ref Ref, items []LearnedItem, label string) (*ArmOut, *ArmOut, error) {
	if err := r.setStore(ctx, items); err != nil {
		return nil, nil, err
	}
	run, err := r.runArm(ctx, r.withCF, s, ref, label)
	if err != nil {
		return nil, nil, err
	}
	gen, err := r.generated(ctx, run)
	if err != nil {
		return nil, nil, err
	}
	if gen.Counterfactual == nil || gen.Counterfactual.Status != "generated" {
		return nil, nil, fmt.Errorf("the knowledge-withheld counterfactual (arm A) was not generated: %+v", gen.Counterfactual)
	}
	b, err := r.arm(ctx, run, gen.Candidates, ids(items))
	if err != nil {
		return nil, nil, err
	}
	a, err := r.arm(ctx, run, gen.Counterfactual.Candidates, nil)
	if err != nil {
		return nil, nil, err
	}
	a.Knowledge = KnowledgeOut{Retrieved: []string{}, Applicable: []string{}, ExceptionBlocked: []string{}, Cited: []string{}}
	return b, a, r.o.Builder.CancelRun(ctx, run)
}

func (r *Runner) armC(ctx context.Context, s Situation, ref Ref, items []LearnedItem) (*ArmOut, error) {
	if err := r.setStore(ctx, items); err != nil {
		return nil, err
	}
	run, err := r.runArm(ctx, r.noCF, s, ref, "C")
	if err != nil {
		return nil, err
	}
	gen, err := r.generated(ctx, run)
	if err != nil {
		return nil, err
	}
	c, err := r.arm(ctx, run, gen.Candidates, ids(items))
	if err != nil {
		return nil, err
	}
	return c, r.o.Builder.CancelRun(ctx, run)
}

// runArm opens a run for the arm on ids fixed by the situation and the arm, and drives it through the orchestrator.
func (r *Runner) runArm(ctx context.Context, svc *orchestrator.Service, s Situation, ref Ref, arm string) (string, error) {
	if err := SeedIDs(ctx, r.o.DB, s.ID+"|"+arm); err != nil {
		return "", err
	}
	r.seq.Reset(s.ID + "|" + arm)
	run, err := r.o.Builder.OpenRun(ctx, ref)
	if err != nil {
		return "", err
	}
	if _, err := svc.Run(ctx, run); err != nil {
		return run, fmt.Errorf("arm %s: %w", arm, err)
	}
	return run, nil
}

type generatedDoc struct {
	Candidates     []workerclient.Candidate `json:"candidates"`
	Counterfactual *struct {
		Status     string                   `json:"status"`
		Candidates []workerclient.Candidate `json:"candidates"`
	} `json:"counterfactual"`
}

func (r *Runner) generated(ctx context.Context, run string) (generatedDoc, error) {
	var raw []byte
	var g generatedDoc
	if err := r.o.DB.QueryRowContext(ctx, `SELECT detail -> 'generated' FROM agent_run_steps WHERE agent_run_id = $1::uuid AND step = 'draft'`, run).Scan(&raw); err != nil {
		return g, err
	}
	return g, json.Unmarshal(raw, &g)
}

// arm scores one arm's candidates: the preferred (worker ranking 1) first draft by the deterministic evals, and the
// knowledge trail of the run.
func (r *Runner) arm(ctx context.Context, run string, cands []workerclient.Candidate, storeIDs []string) (*ArmOut, error) {
	if len(cands) == 0 {
		return nil, errors.New("the worker returned no candidates")
	}
	pref := cands[0]
	for _, c := range cands {
		if c.Ranking < pref.Ranking {
			pref = c
		}
	}
	svc := r.noCF
	findings, err := svc.DeterministicBlocking(ctx, run, pref)
	if err != nil {
		return nil, err
	}
	corr := make([]string, len(findings))
	for i, f := range findings {
		corr[i] = f.EvalType
	}
	k, err := r.knowledgeOf(ctx, run, pref)
	if err != nil {
		return nil, err
	}
	return &ArmOut{Candidate: pref, Candidates: cands, Corrections: corr, Knowledge: k, StoreIDs: storeIDs}, nil
}

func (r *Runner) knowledgeOf(ctx context.Context, run string, pref workerclient.Candidate) (KnowledgeOut, error) {
	var raw []byte
	if err := r.o.DB.QueryRowContext(ctx, `SELECT detail -> 'knowledge_attribution' FROM agent_run_steps WHERE agent_run_id = $1::uuid AND step = 'build_context'`, run).Scan(&raw); err != nil {
		return KnowledgeOut{}, err
	}
	var a struct {
		Retrieved        []string `json:"retrieved"`
		Applicable       []string `json:"applicable"`
		ExceptionBlocked []string `json:"exception_blocked"`
	}
	if err := json.Unmarshal(raw, &a); err != nil {
		return KnowledgeOut{}, err
	}
	nz := func(x []string) []string {
		if x == nil {
			return []string{}
		}
		return x
	}
	return KnowledgeOut{Retrieved: nz(a.Retrieved), Applicable: nz(a.Applicable), ExceptionBlocked: nz(a.ExceptionBlocked), Cited: nz(pref.KnowledgeRefs)}, nil
}
